### PR TITLE
Added ignore command & vanish support

### PR DESCRIPTION
**Pull request by Rubenicos**
Added the following commands (by @Andrius91):
  * `/ignore add <player>` To ignore a player
  * `/ignore remove <player>` To remove an ignored player
  * `/ignore list` To see the list of ignored players

### Update (11-03-2023)
Added vanish support using Essentials system or detecting `/vanish` command in chat.
Added `fake-players` option in config.yml to set names that always be displayed on tab complete.

### CODE REVIEW

**Comment by yakovliam** [comment]
Thanks for the PR. Make sure you pass the build.

**Comment by yakovliam** [comment]
After further review, looks like "com.github.PikaMug:LocaleLib:3.2" isn't found

**Comment by Rubenicos** [comment]
> Thanks for the PR. Make sure you pass the build.

Done, yesterday I forgot to push that commit

**Review by yakovliam — APPROVED** [review]
Approved

**Pull request merged**
